export interface VoiceOption {
  id: string;
  name: string;
  gender: 'Female' | 'Male';
  languageCode: string;
  languageName: string;
  scriptName: string;
  accent: string;
  description: string;
  provider: 'google' | 'elevenlabs';
  samplePreview: string;
  providerVoiceId?: string;
  isPopular?: boolean;
}

export interface LanguageConfig {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  sampleText: string;
  shortPreviewText: string;
  providers: {
    google: boolean;
    elevenlabs: boolean;
  };
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    sampleText: 'नमस्ते! यह इंडियन वॉइस स्टूडियो है। आप अपनी लिखी हुई सामग्री को प्राकृतिक आवाज़ में बदल सकते हैं।',
    shortPreviewText: 'नमस्ते, आपका स्वागत है।',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    sampleText: 'నమస్కారం! ఇది ఇండియన్ వాయిస్ స్టూడియో. మీరు మీ వచనాన్ని సహజమైన స్వరంగా మార్చుకోవచ్చు.',
    shortPreviewText: 'నమస్కారం, మీకు స్వాగతం.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    sampleText: 'வணக்கம்! இது இந்தியன் வாய்ஸ் ஸ்டுடியோ. உங்கள் உரையை இயல்பான குரலாக மாற்றலாம்.',
    shortPreviewText: 'வணக்கம், உங்களை வரவேற்கிறோம்.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    sampleText: 'ನಮಸ್ಕಾರ! ಇದು ಇಂಡಿಯನ್ ವಾಯ್ಸ್ ಸ್ಟುಡಿಯೋ. ನಿಮ್ಮ ಪಠ್ಯವನ್ನು ನೈಸರ್ಗಿಕ ಧ್ವನಿಯಾಗಿ ಪರಿವರ್ತಿಸಬಹುದು.',
    shortPreviewText: 'ನಮಸ್ಕಾರ, ನಿಮಗೆ ಸ್ವಾಗತ.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    sampleText: 'നമസ്കാരം! ഇത് ഇന്ത്യൻ വോയ്സ് സ്റ്റുഡിയോ ആണ്. നിങ്ങളുടെ ടെക്സ്റ്റ് സ്വാഭാവികമായ ശബ്ദമായി മാറ്റാം.',
    shortPreviewText: 'നമസ്കാരം, സ്വാഗതം.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    sampleText: 'नमस्कार! हे इंडियन व्हॉइस स्टुडिओ आहे. तुम्ही तुमचा मजकूर अस्खलित आणि नैसर्गिक आवाजात बदलू शकता.',
    shortPreviewText: 'नमस्कार, आपले स्वागत आहे.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    sampleText: 'নমস্কার! এটি ইন্ডিয়ান ভয়েস স্টুডিও। আপনি আপনার লেখাকে অত্যন্ত সুন্দর ও সাবলীল কণ্ঠে রূপান্তর করতে পারেন।',
    shortPreviewText: 'নমস্কার, আপনাকে স্বাগতম।',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    flag: '🇮🇳',
    sampleText: 'નમસ્તે! આ ઇન્ડિયન વૉઇસ સ્ટુડિયો છે. તમે તમારા લખાણને કુદરતી અવાજમાં પરિવર્તિત કરી શકો છો.',
    shortPreviewText: 'નમસ્તે, તમારું સ્વાગત છે.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    flag: '🇮🇳',
    sampleText: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਇਹ ਇੰਡੀਅਨ ਵੌਇਸ ਸਟੂਡੀਓ ਹੈ। ਤੁਸੀਂ ਆਪਣੇ ਸ਼ਬਦਾਂ ਨੂੰ ਸੁਰੀਲੀ ਅਤੇ ਕੁਦਰਤੀ ਆਵਾਜ਼ ਵਿੱਚ ਬਦਲ ਸਕਦੇ ਹੋ।',
    shortPreviewText: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਜੀ ਆਇਆਂ ਨੂੰ।',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇮🇳',
    sampleText: 'السلام علیکم! یہ انڈین وائس اسٹوڈیو ہے۔ آپ اپنے تحریری الفاظ کو قدرتی اور سحر انگیز آواز میں بدل سکتے ہیں۔',
    shortPreviewText: 'السلام علیکم، خوش آمدید۔',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'en-IN',
    name: 'English (India)',
    nativeName: 'Indian English',
    flag: '🇮🇳',
    sampleText: 'Hello! Welcome to Indian Voice Studio. Convert your text into natural-sounding Indian voices with ease and speed.',
    shortPreviewText: 'Hello, welcome to Indian Voice Studio.',
    providers: { google: true, elevenlabs: true },
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    flag: '🇮🇳',
    sampleText: 'ନମସ୍କାର! ଏହା ଇଣ୍ଡିଆନ୍ ଭଏସ୍ ଷ୍ଟୁଡିଓ।',
    shortPreviewText: 'ନମସ୍କାର, ସ୍ୱାଗତ।',
    providers: { google: false, elevenlabs: false },
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    flag: '🇮🇳',
    sampleText: 'নমস্কাৰ! এইটো ইণ্ডিয়ান ভইচ ষ্টুডিঅ’।',
    shortPreviewText: 'নমস্কাৰ, স্বাগতম।',
    providers: { google: false, elevenlabs: false },
  },
];

export const GOOGLE_VOICES: VoiceOption[] = [
  // Hindi
  {
    id: 'google-hi-ananya',
    name: 'Ananya',
    gender: 'Female',
    languageCode: 'hi',
    languageName: 'Hindi',
    scriptName: 'हिन्दी',
    accent: 'Indian Standard',
    description: 'Warm, natural and conversational voice, perfect for storytelling and podcasts.',
    provider: 'google',
    samplePreview: 'नमस्ते, आपका स्वागत है।',
    isPopular: true,
  },
  {
    id: 'google-hi-aarav',
    name: 'Aarav',
    gender: 'Male',
    languageCode: 'hi',
    languageName: 'Hindi',
    scriptName: 'हिन्दी',
    accent: 'Indian Standard',
    description: 'Clear, crisp and authoritative voice ideal for news and corporate narration.',
    provider: 'google',
    samplePreview: 'नमस्ते, आपका स्वागत है।',
  },
  // Telugu
  {
    id: 'google-te-shravya',
    name: 'Shravya',
    gender: 'Female',
    languageCode: 'te',
    languageName: 'Telugu',
    scriptName: 'తెలుగు',
    accent: 'Coastal Andhra / Telangana',
    description: 'Melodious, warm, and highly expressive for conversational audio.',
    provider: 'google',
    samplePreview: 'నమస్కారం, మీకు స్వాగతం.',
    isPopular: true,
  },
  {
    id: 'google-te-sai',
    name: 'Sai Krishna',
    gender: 'Male',
    languageCode: 'te',
    languageName: 'Telugu',
    scriptName: 'తెలుగు',
    accent: 'Standard Telugu',
    description: 'Confident, articulate, and friendly tone suitable for explainer videos.',
    provider: 'google',
    samplePreview: 'నమస్కారం, మీకు స్వాగతం.',
  },
  // Tamil
  {
    id: 'google-ta-meera',
    name: 'Meera',
    gender: 'Female',
    languageCode: 'ta',
    languageName: 'Tamil',
    scriptName: 'தமிழ்',
    accent: 'Standard Tamil',
    description: 'Pleasant, natural, and clear with refined Tamil pronunciation.',
    provider: 'google',
    samplePreview: 'வணக்கம், உங்களை வரவேற்கிறோம்.',
    isPopular: true,
  },
  {
    id: 'google-ta-karthik',
    name: 'Karthik',
    gender: 'Male',
    languageCode: 'ta',
    languageName: 'Tamil',
    scriptName: 'தமிழ்',
    accent: 'Standard Tamil',
    description: 'Resonant, crisp, and deep voice for educational and broadcast content.',
    provider: 'google',
    samplePreview: 'வணக்கம், உங்களை வரவேற்கிறோம்.',
  },
  // Kannada
  {
    id: 'google-kn-sahana',
    name: 'Sahana',
    gender: 'Female',
    languageCode: 'kn',
    languageName: 'Kannada',
    scriptName: 'ಕನ್ನಡ',
    accent: 'Standard Kannada',
    description: 'Gentle, articulate, and soothing tone with authentic cadence.',
    provider: 'google',
    samplePreview: 'ನಮಸ್ಕಾರ, ನಿಮಗೆ ಸ್ವಾಗತ.',
    isPopular: true,
  },
  {
    id: 'google-kn-manjunath',
    name: 'Manjunath',
    gender: 'Male',
    languageCode: 'kn',
    languageName: 'Kannada',
    scriptName: 'ಕನ್ನಡ',
    accent: 'Standard Kannada',
    description: 'Authoritative and steady voice for instructional and documentary content.',
    provider: 'google',
    samplePreview: 'ನಮಸ್ಕಾರ, ನಿಮಗೆ ಸ್ವಾಗತ.',
  },
  // Malayalam
  {
    id: 'google-ml-arya',
    name: 'Arya',
    gender: 'Female',
    languageCode: 'ml',
    languageName: 'Malayalam',
    scriptName: 'മലയാളം',
    accent: 'Standard Malayalam',
    description: 'Soft, fluent, and highly natural cadence for audiobooks and media.',
    provider: 'google',
    samplePreview: 'നമസ്കാരം, സ്വാഗതം.',
    isPopular: true,
  },
  {
    id: 'google-ml-vishnu',
    name: 'Vishnu',
    gender: 'Male',
    languageCode: 'ml',
    languageName: 'Malayalam',
    scriptName: 'മലയാളം',
    accent: 'Standard Malayalam',
    description: 'Dynamic, confident tone with crystal-clear Malayalam diction.',
    provider: 'google',
    samplePreview: 'നമസ്കാരം, സ്വാഗതം.',
  },
  // Marathi
  {
    id: 'google-mr-tanvi',
    name: 'Tanvi',
    gender: 'Female',
    languageCode: 'mr',
    languageName: 'Marathi',
    scriptName: 'मराठी',
    accent: 'Standard Marathi',
    description: 'Poised, expressive, and clear tone with rich Marathi inflection.',
    provider: 'google',
    samplePreview: 'नमस्कार, आपले स्वागत आहे.',
    isPopular: true,
  },
  {
    id: 'google-mr-rohan',
    name: 'Rohan',
    gender: 'Male',
    languageCode: 'mr',
    languageName: 'Marathi',
    scriptName: 'मराठी',
    accent: 'Standard Marathi',
    description: 'Energetic, modern, and engaging voice for promotions and explainers.',
    provider: 'google',
    samplePreview: 'नमस्कार, आपले स्वागत आहे.',
  },
  // Bengali
  {
    id: 'google-bn-poulomi',
    name: 'Poulomi',
    gender: 'Female',
    languageCode: 'bn',
    languageName: 'Bengali',
    scriptName: 'বাংলা',
    accent: 'Standard Bengali',
    description: 'Lyrical, sweet, and articulate voice for literary and commercial speech.',
    provider: 'google',
    samplePreview: 'নমস্কার, আপনাকে স্বাগতম।',
    isPopular: true,
  },
  {
    id: 'google-bn-subhash',
    name: 'Subhash',
    gender: 'Male',
    languageCode: 'bn',
    languageName: 'Bengali',
    scriptName: 'বাংলা',
    accent: 'Standard Bengali',
    description: 'Classic, baritone, and steady voice suitable for news and narrations.',
    provider: 'google',
    samplePreview: 'নমস্কার, আপনাকে স্বাগতম।',
  },
  // Gujarati
  {
    id: 'google-gu-dhwani',
    name: 'Dhwani',
    gender: 'Female',
    languageCode: 'gu',
    languageName: 'Gujarati',
    scriptName: 'ગુજરાતી',
    accent: 'Standard Gujarati',
    description: 'Bright, cheerful, and engaging voice with natural conversational flow.',
    provider: 'google',
    samplePreview: 'નમસ્તે, તમારું સ્વાગત છે.',
    isPopular: true,
  },
  {
    id: 'google-gu-chirag',
    name: 'Chirag',
    gender: 'Male',
    languageCode: 'gu',
    languageName: 'Gujarati',
    scriptName: 'ગુજરાતી',
    accent: 'Standard Gujarati',
    description: 'Warm, trustworthy, and clear voice for business and educational media.',
    provider: 'google',
    samplePreview: 'નમસ્તે, તમારું સ્વાગત છે.',
  },
  // Punjabi
  {
    id: 'google-pa-harleen',
    name: 'Harleen',
    gender: 'Female',
    languageCode: 'pa',
    languageName: 'Punjabi',
    scriptName: 'ਪੰਜਾਬੀ',
    accent: 'Standard Punjabi',
    description: 'Vibrant, friendly, and lively with natural Punjabi rhythm.',
    provider: 'google',
    samplePreview: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਜੀ ਆਇਆਂ ਨੂੰ।',
    isPopular: true,
  },
  {
    id: 'google-pa-gurpreet',
    name: 'Gurpreet',
    gender: 'Male',
    languageCode: 'pa',
    languageName: 'Punjabi',
    scriptName: 'ਪੰਜਾਬੀ',
    accent: 'Standard Punjabi',
    description: 'Bold, resonant, and engaging for announcements and narrations.',
    provider: 'google',
    samplePreview: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਜੀ ਆਇਆਂ ਨੂੰ।',
  },
  // Urdu
  {
    id: 'google-ur-farida',
    name: 'Farida',
    gender: 'Female',
    languageCode: 'ur',
    languageName: 'Urdu',
    scriptName: 'اردو',
    accent: 'Standard Urdu',
    description: 'Polished, elegant, and poetic diction with refined pronunciation.',
    provider: 'google',
    samplePreview: 'السلام علیکم، خوش آمدید۔',
    isPopular: true,
  },
  {
    id: 'google-ur-tariq',
    name: 'Tariq',
    gender: 'Male',
    languageCode: 'ur',
    languageName: 'Urdu',
    scriptName: 'اردو',
    accent: 'Standard Urdu',
    description: 'Deep, sophisticated, and dignified tone for literature and media.',
    provider: 'google',
    samplePreview: 'السلام علیکم، خوش آمدید۔',
  },
  // English (India)
  {
    id: 'google-en-in-priya',
    name: 'Priya',
    gender: 'Female',
    languageCode: 'en-IN',
    languageName: 'English (India)',
    scriptName: 'Indian English',
    accent: 'Urban Indian Accent',
    description: 'Professional, articulate Indian English voice ideal for corporate presentations.',
    provider: 'google',
    samplePreview: 'Hello, welcome to Indian Voice Studio.',
    isPopular: true,
  },
  {
    id: 'google-en-in-vikram',
    name: 'Vikram',
    gender: 'Male',
    languageCode: 'en-IN',
    languageName: 'English (India)',
    scriptName: 'Indian English',
    accent: 'Urban Indian Accent',
    description: 'Confident, modern, and engaging Indian English voice for tutorials and ads.',
    provider: 'google',
    samplePreview: 'Hello, welcome to Indian Voice Studio.',
  },
];

export const ELEVENLABS_DEFAULT_VOICES: VoiceOption[] = [
  {
    id: 'eleven-ananya',
    providerVoiceId: '21m00Tcm4TlvDq8ikWAM', // Rachel / Multilingual
    name: 'Ananya (Eleven)',
    gender: 'Female',
    languageCode: 'hi',
    languageName: 'Hindi',
    scriptName: 'हिन्दी',
    accent: 'Multilingual Natural',
    description: 'Ultra-realistic neural synthesis with emotional depth and nuance.',
    provider: 'elevenlabs',
    samplePreview: 'नमस्ते, आपका स्वागत है।',
    isPopular: true,
  },
  {
    id: 'eleven-aarav',
    providerVoiceId: 'pNInz6obpgDQGcFmaJgB', // Adam / Multilingual
    name: 'Aarav (Eleven)',
    gender: 'Male',
    languageCode: 'hi',
    languageName: 'Hindi',
    scriptName: 'हिन्दी',
    accent: 'Multilingual Deep',
    description: 'Rich, deep, conversational voice powered by Eleven Multilingual v2.',
    provider: 'elevenlabs',
    samplePreview: 'नमस्ते, आपका स्वागत है।',
  },
  {
    id: 'eleven-priya',
    providerVoiceId: 'EXAVITQu4vr4xnSDxMaL', // Bella / Multilingual
    name: 'Priya (Eleven)',
    gender: 'Female',
    languageCode: 'en-IN',
    languageName: 'English (India)',
    scriptName: 'Indian English',
    accent: 'Indian English Multilingual',
    description: 'Gentle, expressive, and studio-grade quality for narrations.',
    provider: 'elevenlabs',
    samplePreview: 'Hello, welcome to Indian Voice Studio.',
    isPopular: true,
  },
  {
    id: 'eleven-vikram',
    providerVoiceId: 'TxGEqnHWrfWFTfGW9XjX', // Josh / Multilingual
    name: 'Vikram (Eleven)',
    gender: 'Male',
    languageCode: 'en-IN',
    languageName: 'English (India)',
    scriptName: 'Indian English',
    accent: 'Indian English Multilingual',
    description: 'Dynamic, confident tone with rich harmonics.',
    provider: 'elevenlabs',
    samplePreview: 'Hello, welcome to Indian Voice Studio.',
  },
  {
    id: 'eleven-shravya',
    providerVoiceId: 'AZnzlk1XvdvUeBnXmlld', // Domi
    name: 'Shravya (Eleven)',
    gender: 'Female',
    languageCode: 'te',
    languageName: 'Telugu',
    scriptName: 'తెలుగు',
    accent: 'Multilingual Expressive',
    description: 'Strong, articulate, and clear voice for multilingual narration.',
    provider: 'elevenlabs',
    samplePreview: 'నమస్కారం, మీకు స్వాగతం.',
  },
  {
    id: 'eleven-karthik',
    providerVoiceId: 'ErXwobaYiN019PkySvjV', // Antoni
    name: 'Karthik (Eleven)',
    gender: 'Male',
    languageCode: 'ta',
    languageName: 'Tamil',
    scriptName: 'தமிழ்',
    accent: 'Multilingual Natural',
    description: 'Well-modulated and warm cadence across Indian languages.',
    provider: 'elevenlabs',
    samplePreview: 'வணக்கம், உங்களை வரவேற்கிறோம்.',
  },
];
